### ISSUE TITLE
Delete resourceclaims on job completion or termination

### ISSUE THREAD

**Issue by asm582** [kubernetes-sigs/dra-example-driver#42]
When batch/v1 job requesting a GPU claim through resourceclaim is completed, the underlying resourceclaim is still in `allocated, reserved` state. This will lead to resource wastage. I think we should delete the claim if the object consuming the resourceclaim completes or terminates

**Comment by asm582** [comment]
Can you share more light why claim should not be deleted?

**Comment by klueska** [comment]
Just as with any other API server object -- if the user creates the claim, it should be the user that also deletes it.  Claims created as part of a `ClaimTemplate` will be cleaned up by the system because the claims were created by the system. But claims created by the user (e.g. via a `kubectl apply`) will only be deleted upon request by the user (e.g. via a `kubectl delete`).

**Comment by byako** [comment]
Which version of Kubernetes was used?
I just tested with 1.28 and our latest DRA driver. Just like I remembered - this has been fixed some time ago - 1.27 or 1.28, the deallocatoin part at least. The Claims created manually stay, but they are no longer allocated, and  Claims generated even get deleted.

**Comment by kannon92** [comment]
@klueska is this the issue you had in mind? https://github.com/kubernetes/kubernetes/issues/120756
